<?php
/**
 * Created by PhpStorm.
 * User: bert
 * Date: 7/27/16
 * Time: 5:45 PM
 */

namespace chapter10\decorator;


class PollutedPlains extends Plains{

  public function getWealthFactor() {
    return parent::getWealthFactor() - 4; // TODO: Change the autogenerated stub
  }


}